all:rearrang q_182 q_1.7.5 q_183 q_184

rearrang:rearrang.c
	gcc rearrang.c -o rearrang

q_182:q_182.c
	gcc q_182.c -o q_182

q_1.7.5:q_1.7.5.c
	gcc q_1.7.5.c -o q_1.7.5

q_183:q_183.c
	gcc q_183.c -o q_183

q_184:q_184.c
	gcc q_184.c -o q_184

clean:
	rm q_182 q_183 q_184 rearrang q_1.7.5
