all: test1 q_10 q_1 q_2 q_3 q_3_answer q_4 q_5 q_6

test1:test1.c
	gcc test1.c -o test1

q_10:q_10.c
	gcc q_10.c -o q_10

q_1:q_1.c
	gcc q_1.c -o q_1

q_2:q_2.c
	gcc q_2.c -o q_2

q_3:q_3.c
	gcc q_3.c -g -o q_3

q_3_answer:q_3_answer.c
	gcc q_3_answer.c -g -o q_3_answer

q_4:q_4.c
	gcc q_4.c -g -o q_4

q_5:q_5.c
	gcc q_5.c -g -o q_5

q_6:q_6.c
	gcc q_6.c -g -o q_6

clean:
	rm test1 q_10 q_1 q_2 q_3 q_3_answer q_4 q_5 q_6
