all: btoa fibonacci va_average

btoa:btoa.c
	gcc -g btoa.c -o btoa

fibonacci:fibonacci.c
	gcc -g fibonacci.c -o fibonacci

va_average:va_average.c
	gcc -g va_average.c -o average

clean:
	rm btoa fibonacci va_average
